package com.resonote.core.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Generated from the frozen brand seeds documented in design/theme-generator.
internal val ResonoteLightColorScheme: ColorScheme = lightColorScheme(
    primary = Color(0xFFAE2A4B),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9DD),
    onPrimaryContainer = Color(0xFF400012),
    inversePrimary = Color(0xFFFFB2BC),
    secondary = Color(0xFF66558F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE9DDFF),
    onSecondaryContainer = Color(0xFF210F47),
    tertiary = Color(0xFF855300),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDDB8),
    onTertiaryContainer = Color(0xFF2A1700),
    background = Color(0xFFFFFBFF),
    onBackground = Color(0xFF201A1B),
    surface = Color(0xFFFFF8F7),
    onSurface = Color(0xFF201A1B),
    surfaceVariant = Color(0xFFF4DDDF),
    onSurfaceVariant = Color(0xFF524344),
    surfaceTint = Color(0xFFAE2A4B),
    inverseSurface = Color(0xFF362F2F),
    inverseOnSurface = Color(0xFFFBEEEE),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF847374),
    outlineVariant = Color(0xFFD7C1C3),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F7),
    surfaceDim = Color(0xFFE3D7D7),
    surfaceContainer = Color(0xFFF8EBEB),
    surfaceContainerHigh = Color(0xFFF2E5E5),
    surfaceContainerHighest = Color(0xFFECE0E0),
    surfaceContainerLow = Color(0xFFFEF1F1),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFFFFD9DD),
    primaryFixedDim = Color(0xFFFFB2BC),
    onPrimaryFixed = Color(0xFF400012),
    onPrimaryFixedVariant = Color(0xFF8D0D35),
    secondaryFixed = Color(0xFFE9DDFF),
    secondaryFixedDim = Color(0xFFD0BCFE),
    onSecondaryFixed = Color(0xFF210F47),
    onSecondaryFixedVariant = Color(0xFF4E3D75),
    tertiaryFixed = Color(0xFFFFDDB8),
    tertiaryFixedDim = Color(0xFFFDB965),
    onTertiaryFixed = Color(0xFF2A1700),
    onTertiaryFixedVariant = Color(0xFF653E00),
)

internal val ResonoteDarkColorScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFFFFB2BC),
    onPrimary = Color(0xFF670022),
    primaryContainer = Color(0xFF8D0D35),
    onPrimaryContainer = Color(0xFFFFD9DD),
    inversePrimary = Color(0xFFAE2A4B),
    secondary = Color(0xFFD0BCFE),
    onSecondary = Color(0xFF37265D),
    secondaryContainer = Color(0xFF4E3D75),
    onSecondaryContainer = Color(0xFFE9DDFF),
    tertiary = Color(0xFFFDB965),
    onTertiary = Color(0xFF472A00),
    tertiaryContainer = Color(0xFF653E00),
    onTertiaryContainer = Color(0xFFFFDDB8),
    background = Color(0xFF201A1B),
    onBackground = Color(0xFFECE0E0),
    surface = Color(0xFF181212),
    onSurface = Color(0xFFECE0E0),
    surfaceVariant = Color(0xFF524344),
    onSurfaceVariant = Color(0xFFD7C1C3),
    surfaceTint = Color(0xFFFFB2BC),
    inverseSurface = Color(0xFFECE0E0),
    inverseOnSurface = Color(0xFF362F2F),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF9F8C8E),
    outlineVariant = Color(0xFF524344),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3F3738),
    surfaceDim = Color(0xFF181212),
    surfaceContainer = Color(0xFF241E1F),
    surfaceContainerHigh = Color(0xFF2F2829),
    surfaceContainerHighest = Color(0xFF3A3334),
    surfaceContainerLow = Color(0xFF201A1B),
    surfaceContainerLowest = Color(0xFF120D0D),
    primaryFixed = Color(0xFFFFD9DD),
    primaryFixedDim = Color(0xFFFFB2BC),
    onPrimaryFixed = Color(0xFF400012),
    onPrimaryFixedVariant = Color(0xFF8D0D35),
    secondaryFixed = Color(0xFFE9DDFF),
    secondaryFixedDim = Color(0xFFD0BCFE),
    onSecondaryFixed = Color(0xFF210F47),
    onSecondaryFixedVariant = Color(0xFF4E3D75),
    tertiaryFixed = Color(0xFFFFDDB8),
    tertiaryFixedDim = Color(0xFFFDB965),
    onTertiaryFixed = Color(0xFF2A1700),
    onTertiaryFixedVariant = Color(0xFF653E00),
)

internal val ResonoteAmoledColorScheme: ColorScheme = ResonoteDarkColorScheme.copy(
    background = Color.Black,
    surface = Color.Black,
    surfaceDim = Color.Black,
    surfaceContainerLowest = Color.Black,
    surfaceContainerLow = Color(0xFF120D0D),
    surfaceContainer = Color(0xFF181212),
    surfaceContainerHigh = Color(0xFF201A1B),
    surfaceContainerHighest = Color(0xFF2F2829),
    surfaceBright = Color(0xFF3F3738),
)
