syntax = "proto3";

option java_package = "com.resonote.core.datastore.proto";
option java_multiple_files = true;

message PlaybackPreferences {
  uint32 playback_speed_percent = 1;
  string online_playback_quality = 2;
  string playback_mode = 3;
  bool gapless_enabled = 4;
  string crossfade_duration = 5;
  bool loudness_normalization_enabled = 6;
  string audio_focus_policy = 7;
  bool gapless_configured = 8;
  bool equalizer_enabled = 9;
  sint32 equalizer_low_db = 10;
  sint32 equalizer_mid_db = 11;
  sint32 equalizer_high_db = 12;
  bool equalizer_custom = 13;
}
